/**
 * Type definitions for the Demo Account System
 * Provides comprehensive type safety for demo data management, restoration, and AI generation
 */

/**
 * Demo account configuration
 */
export interface DemoAccountConfig {
  email: string
  password: string
  name: string
  role: 'Hospital Administrator' | 'Logistics Manager' | 'Compliance Officer'
}

/**
 * Auto-detection configuration
 */
export interface AutoDetectConfig {
  enabled: boolean
  checkInterval: string
  excludeTables: string[]
}

/**
 * AI generation configuration
 */
export interface AIGenerationConfig {
  enabled: boolean
  provider: 'openai' | 'anthropic'
  model: string
  recordsPerTable: {
    min: number
    max: number
  }
  temperature: number
  fallbackToTemplate: boolean
}

/**
 * Restoration configuration
 */
export interface RestorationConfig {
  automatic: boolean
  onLogout: boolean
  manualEnabled: boolean
  validateAfter: boolean
}

/**
 * Notification configuration
 */
export interface NotificationConfig {
  slack?: string
  email?: string
}

/**
 * Complete demo system configuration
 */
export interface DemoConfig {
  account: DemoAccountConfig
  autoDetect: AutoDetectConfig
  aiGeneration: AIGenerationConfig
  restoration: RestorationConfig
  notifications: NotificationConfig
}

/**
 * Table coverage information
 */
export interface TableCoverage {
  table: string
  recordCount: number
  generatedBy: 'ai' | 'manual' | 'template'
  generatedAt: string
  schemaHash: string
}

/**
 * Seed data metadata
 */
export interface SeedDataMetadata {
  version: string
  lastUpdated: string
  autoGenerated: string[]
  manuallyMaintained: string[]
  coverage: Record<string, TableCoverage>
}

/**
 * Restoration error details
 */
export interface RestorationError {
  table: string
  error: string
  phase: 'backup' | 'delete' | 'restore' | 'validate'
}

/**
 * Restoration result
 */
export interface RestorationResult {
  success: boolean
  tablesRestored: string[]
  recordsRestored: number
  duration: number
  errors: RestorationError[]
}

/**
 * Demo status response
 */
export interface DemoStatusResponse {
  isDemo: boolean
  coverage: number
  lastRestore: string | null
  version: string
}

/**
 * Sync result from auto-detection
 */
export interface SyncResult {
  success: boolean
  newTables: string[]
  seedsGenerated: number
  errors: string[]
}

/**
 * Table schema information
 */
export interface TableSchema {
  tableName: string
  columns: ColumnSchema[]
  primaryKey: string[]
  foreignKeys: ForeignKeySchema[]
  constraints: ConstraintSchema[]
}

/**
 * Column schema details
 */
export interface ColumnSchema {
  name: string
  type: string
  nullable: boolean
  defaultValue: string | null
  isPrimaryKey: boolean
  isForeignKey: boolean
}

/**
 * Foreign key relationship
 */
export interface ForeignKeySchema {
  columnName: string
  referencedTable: string
  referencedColumn: string
}

/**
 * Constraint information
 */
export interface ConstraintSchema {
  name: string
  type: 'check' | 'unique' | 'primary_key' | 'foreign_key'
  definition: string
}

/**
 * Seed data for a table
 */
export interface TableSeedData {
  table: string
  records: Record<string, unknown>[]
  metadata: {
    generatedBy: 'ai' | 'manual' | 'template'
    generatedAt: string
    recordCount: number
  }
}

/**
 * AI generation request
 */
export interface AIGenerationRequest {
  table: string
  schema: TableSchema
  context: string
  recordCount: number
}

/**
 * AI generation response
 */
export interface AIGenerationResponse {
  success: boolean
  records: Record<string, unknown>[]
  error?: string
}

/**
 * Health check result
 */
export interface HealthCheckResult {
  healthy: boolean
  issues: HealthIssue[]
  autoFixed: HealthIssue[]
}

/**
 * Individual health issue
 */
export interface HealthIssue {
  severity: 'critical' | 'warning' | 'info'
  category: 'missing_seed' | 'corrupted_data' | 'schema_mismatch' | 'orphaned_records' | 'fk_violation'
  description: string
  table?: string
  autoFixable: boolean
}

/**
 * Demo restoration record for tracking
 */
export interface DemoRestoration {
  id: string
  user_id: string
  restored_at: string
  tables_restored: string[]
  records_restored: number
  duration_ms: number
  success: boolean
  error: string | null
  triggered_by: 'logout' | 'manual' | 'api' | 'scheduled'
}

/**
 * Demo seed version record
 */
export interface DemoSeedVersion {
  id: string
  table_name: string
  version: string
  generated_by: 'ai' | 'manual' | 'template'
  generated_at: string
  record_count: number
  schema_hash: string
}
